version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    user: root
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    user: root
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      # 监听所有网络接口
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      # 外部机器使用的ip访问
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.2.64.91:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
